Update main_mlsaprofiemaker.yml

diff --git a/.github/workflows/main_mlsaprofiemaker.yml b/.github/workflows/main_mlsaprofiemaker.yml
--- a/.github/workflows/main_mlsaprofiemaker.yml
+++ b/.github/workflows/main_mlsaprofiemaker.yml
@@ -1,7 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
-
 name: Build and deploy Python app to Azure Web App - mlsaprofiemaker
 
 on:
@@ -28,7 +24,14 @@ jobs:
           source venv/bin/activate
       
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y libjpeg-dev  # Install libjpeg-dev
+          pip install -r requirements.txt || true  # Use '|| true' to continue on error
+          if [ $? -ne 0 ]; then
+            echo "Retry installing dependencies..."
+            pip install -r requirements.txt  # Retry installation
+          fi
         
       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
       
